spring:
  security:
    enabled: false
  data:
    mongodb:
      uri: ${MONGO_URI}

management:
  security:
    enabled: false

security:
  basic:
    enabled: false

jwt:
  secret: ${JWT_SECRET}